
export class listingBuyer {
  key: string;
  Firstname: string;
  Lastname: string;
  Email: string;
  DOB: string;
  Password: string;
  Confirm: string;
  financial: string;
  ChainStatus: string = "First Time Buyer";
  cars: string;
  FinancialPosition: any ;
  Type: string = "Buying to Live";
  Position: string = "Cash Buyer";
  CurrentAddress: string;
  PropertyType: string = "Flat";
  Country: string;
  addressname: string;
  Currentstate: string;
  CurrentTown: string;
  Currentpostcode: any;
  Lookingpostcode: any;
  LookingTown: any;
  Lookingstate: any;
  LookingAddress: any;
  latitude: any;
  longitude: any;
  SearchRadius:  string  ="This postcode only";
  PriceRange: any = 0;
  Validity: any;
  Conditions: any;
  Bcurrent: string;
  Blooking: string;
  MinAmount: string;
  MaxAmount: string;
  LookingStreetname:string;
  phonenumber:number;
  otherInfo:string;
  active = true;
  static title: string;
  static Firstname: string;
  result: any;
  data: any;
  static Lookingpostcode: string;
  UserId : any;
  Roomsmax;
  Roommin:string;
  Ownership:string;
  Minbathroom:any;
  Maxbathroom:string;
  Minreception:string;
  Maxreception:string;
  features:string;
  Currentcountry:string;
  username:any;
  useremail:any;
  userdob:any;
  userphone:any;
  usertitle:any;
  title:any;
  PropertyFor:any
}
